Blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import patterns, include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='index')),

]

blog/urls.py
from django.conf.urls import patterns, include, url
from blog.views import *
from blog.models import *


urlpatterns = patterns('',
   url(r'^post/(?P<id_post>\d+)/$', 
       'blog.views.post', 
       name='post'),
   url(r"", "blog.views.index"),
)

blog/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.mail import send_mail
from django import forms

#notify = False

class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to = 'blog/static/fotos', default = 'blog/static/fotos/index.png')
    imagen = models.ImageField(upload_to = 'blog/static/fotos', default = 'blog/static/fotos/cambio.jpeg')
    nombre_imagen = models.CharField(max_length=80, default= 'juan.png')
    url_post=models.CharField(max_length=60, null=True,blank=True)
    
    def __str__(self):
        return self.title




### Admin

class PostAdmin(admin.ModelAdmin):
    search_fields = ["title"]
    display_fields = ["title", "created","categorias","nombre_imagen","imagen",]
    
#NO IMPLEMENTADO    
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.body[:60]))

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
import time
from calendar import month_name

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.template import RequestContext

from blog.models import *
from django.forms import ModelForm
from django.template import loader

# Create your views here.



def index(request):
    """Main listing."""
    context = RequestContext(request)
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, 5)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    context.update(dict(posts=posts, user=request.user,
                        post_list=posts.object_list, months=mkmonth_lst()))
    return render_to_response("list.html", context)





def post(request, id_post):
    """Single post with comments and a comment form."""
    context = RequestContext(request)
    post = Post.objects.get(pk=id_post)
    print (request.method)
    if 'POST' in request.method:
        author = request.POST['author']
        content = request.POST['content']
        comentario = Comment(author=author, 
                             body=content,
                             post=post)
        comentario.save()
    comments = Comment.objects.filter(post=post)
    #form=CommentForm()
    context.update(dict(post=post, user=request.user, comments=comments))#, comments=comments)
    context.update(csrf(request))
    return render_to_response("post.html", context)








def mkmonth_lst():
    """Make a list of months to show archive links."""
    if not Post.objects.count(): return []

    # set up vars
    year, month = time.localtime()[:2]
    first = Post.objects.order_by("created")[0]
    fyear = first.created.year
    fmonth = first.created.month
    months = []

    # loop over years and months
    for y in range(year, fyear-1, -1):
        start, end = 12, 0
        if y == year: start = month
        if y == fyear: end = fmonth-1

        for m in range(start, end, -1):
            months.append((y, m, month_name[m]))
    return months

def month(request, year, month):
    """Monthly archive."""
    posts = Post.objects.filter(created__year=year, created__month=month)
    return render_to_response("list.html", dict(post_list=posts, user=request.user,
                                                months=mkmonth_lst(), archive=True))

blog/templates/base.html
{% load static %}
{% load staticfiles %}
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 
<head>
<script src="js/jquery-3.1.0.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<link type="text/css" href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" media="screen,projection"/>
<title>Blog Django </title>
    
 
    
</head>
<body style="background-color:;">
    
   <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a href="http://127.0.0.1:8000/" class="navbar-brand">Facu Ferreyra</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="http://127.0.0.1:8000/post/5/" >Calculadora</a></li>
                <li><a href="http://127.0.0.1:8000/post/4/" >Cambio</a></li>
                <li><a href="http://127.0.0.1:8000/post/3/" >Formulario</a></li>
                <li><a href="http://127.0.0.1:8000/post/2/" >Marco electronico</a></li>
                <li><a href="http://127.0.0.1:8000/post/1/" >Cronometro</a></li>
                    </a>

                    </ul>
                 </li>              
             </ul>
                        
           

        </div>
    </div>
</div><br><br><br>
    {% block content %}{% endblock %}

         
</body>
    

</html>

blog/templates/calc.html
{% load static %}
{% load staticfiles %}
<html>
    </head>
    <body>
        <div class="title">
        </div>
        <br>
        <div class="calc"> 
            <form name="fo" >
            <link type="text/css" href="{% static 'css/calc.css'%}" rel="stylesheet" media="screen,projection"/>
         <table>
            <td class=inputstyle colspan="5"><input type="text" name="valores" id="valores" onkeypress ="return solonumeros(event)" ></td> 
            <br>
            <tr>    
            <td><input type="button" class="button black" value="7" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="8" onclick="print(value)" ></td> 
            <td><input type="button" class="button black" value="9" onclick="print(value)" ></td>
            <td><input type="button" class="button pink" value="+" onclick="print(value)" ></td>
            <td><input type="button" class="button pink" value=" -" onclick="print(value)" ></td>
             </tr>
            <tr>
            <br>
            <td><input type="button" class="button black" value="4" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="5" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="6" onclick="print(value)" ></td>
            <td><input type="button" class="button pink" value="*" onclick="print(value)" ></td>
            <td><input type="button" class="button pink" value=" /" onclick="print(value)" ></td>
            </tr>
            <tr>
            <td><input type="button"class="button black" value="1" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="2" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="3" onclick="print(value)" ></td>
           <td><input type="button" class="button pink" value="(" onclick="print(value)" ></td>
            <td><input type="button" class="button pink" value=" )" onclick="print(value)" ></td>
            </tr>    
            <tr>
            <td><input type="button" class="button black" value=" ." onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="0" onclick="print(value)" ></td>
            <td><input type="button" class="button black" value="<-" onclick="borrar()" ></td>
            <td><input type="button" class="button gray" value="c" onclick="borrartodo()" ></td>
            <td><input type="button"  class="button orange" value="=" onclick="resultado()" ></td>
            </tr>

    </table>
                  <select id="select" name="cssCambiar" onChange="changeCss();">
            <option value="./static/css/calc.css">Comun</option>
            <option value="/home/facu/Escritorio/Blog/blog/static/css/calc2.css">rojo</option>
            <option value="{% static 'css/calc3.css'%}">verde</option>
        </select>
            
            </form>
        </div>
        <script>
        
    var res="";
    
    function borrartodo(){
        document.fo.valores.value="";
    }
    
    function borrar(){
        
        var anterior= document.fo.valores.value;
        
        var nuevo=anterior.substring(0,anterior.length-1);
        
        document.getElementById("valores").value=nuevo;
        
    }
    
    function resultado(){
    
        
           
        res = document.fo.valores.value;
        
        document.getElementById("valores").value=res;
        eval(res);
        
        
    
        document.fo.valores.value=eval(res);
        
        
    }
    
    function solonumeros(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="0123456789+-*/().";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
        
    function print(num){
            
        
                
        var anterior= document.fo.valores.value;
        
        document.getElementById("valores").value=anterior+num;
   
    }
    
    function changeCss(){
		var link = document.getElementById("cssArchivo");
		var css = document.fo.cssCambiar;
		link.href = css.value;		
	};
        </script>
      
        </body>
</html>

blog/templates/conversor.html
{% load static %}
{% load staticfiles %}
<html>
    <head>
    <link type="text/css" href="{% static 'css/conversor.css'%}" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <div class="conv">
            <form name="fo">
                 <td colspan="5"><input onkeypress="return solonumeros(event)" type="text" name="valores1" id="valores1" ></td> <br><br>
    <select class="selec1" name="monedas1" onclick="cambio()">
            <option value="1">Dolares</option>
            <option value="1.13">Euro</option>
            <option value="0.27">Reales</option>
            <option value="0.0677">Pesos Argentinos</option>
            <option value="0.0015">Chilenos</option>
            <option value="0.031">Uruguayos</option>
        </select><br><br>
     <td  colspan="5"><input onkeypress="return solonumeros2(event)" type="text" name="valores2" id="valores2" ></td><br><br>
    
    <select class="selec2"  name="monedas2" onclick="cambio()" >
            <option value="1">Dolares</option>
            <option value="1.13">Euro</option>
            <option value="0.27">Reales</option>
            <option value="0.0677">Pesos Argentinos</option>
            <option value="0.0015">Chilenos</option>
            <option value="0.031">Uruguayos</option>
        </select>
    
    <input onclick="borrar()" value="Borrar" type="button" id="button">
    
       
     <br>    
</form>
        </div>
    <script>
        function borrar(){
        document.fo.valores1.value= "";
        document.fo.valores2.value= "";
    }

    function solonumeros(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="0123456789.";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
    
    function solonumeros2(e){
        
        key=e.keyCode || e.which;
        
        teclado=String.fromCharCode(key);
        
        numeros="";
       
        
        if(numeros.indexOf(teclado)==-1 ){
            return false;
        }
    }
    
    
    function cambio(){
        var cambiar = document.fo.valores1.value;
        
        var ayuda1 = document.fo.monedas1.value;
        
        var ayuda2 = document.fo.monedas2.value;
        
        var pri =eval(cambiar*ayuda1);
        var seg =eval(pri/ayuda2);
        
        document.getElementById("valores2").value=seg;
        
    }
    
    </script>
    </body>
</html>

blog/templates/cronometro.html
{% load static %}
{% load staticfiles %}
<html>
    <head>
    <title>Mi blog</title>
   <link type="text/css" href="{% static 'css/Cronometro.css'%}" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <br>
            <br>
            <div class="base"></div>
        <div class="crm" id="reloj">
        <p>0 : 00 : 00 : 000</p>

        
        </div>

        <form name="cron" action="#">
        <input class="empezar" type="button" value="Empezar" name="boton1"    />
        <input class="parar" type="button" value="Parar" name="boton2"  />

        </form>
            <script>
                  
    window.onload = function() {

    visor=document.getElementById("reloj"); //localizar pantalla del reloj
    
    document.cron.boton1.onclick = activo; 
    document.cron.boton2.onclick = pausa;
    //estado inicial de los botones
    document.cron.boton1.disabled=false;
    document.cron.boton2.disabled=true;
    document.cron.boton3.disabled=true;
        
    var marcha=0; //control del temporizador
    var cro=0;    //estado inicial del cronómetro.
    }
    
    
    
    //botón Empezar / Reiniciar
    function activo (){   
         if (document.cron.boton1.value=="Empezar") { //botón en "Empezar"
            empezar() //ir  la función empezar
            }
         else {  //Botón en "Reiniciar"
            reiniciar()  //ir a la función reiniciar
            }
         }
    //botón pausa / continuar
    function pausa (){ 
         if (marcha==0) { //con el boton en "continuar"
            continuar() //ir a la función continuar
            }
         else {  //con el botón en "parar"
            parar()  //ir a la funcion parar
            }
         }
    
    //Botón 1: Estado empezar: Poner en marcha el crono
    function empezar() {
          emp=new Date(); //fecha inicial (en el momento de pulsar)
          elcrono=setInterval(tiempo,10); //poner en marcha el temporizador.
          marcha=1; //indicamos que se ha puesto en marcha.
          document.cron.boton1.value="Reiniciar"; //Cambiar estado del botón
          document.cron.boton2.disabled=false; //activar botón de pausa
          document.cron.boton3.disabled=false; //activar botón de vuelta
          }
    
    
    //función del temporizador	
    function tiempo() { 
         actual=new Date(); //fecha a cada instante	
            //tiempo del crono (cro) = fecha instante (actual) - fecha inicial (emp)	
         cro=actual-emp; //milisegundos transcurridos.	
         cr=new Date(); //pasamos el num. de milisegundos a objeto fecha.	
         cr.setTime(cro); 
            //obtener los distintos formatos de la fecha:	
         cs=cr.getMilliseconds(); //milisegundos 	
         //cs=cs/10; //paso a centésimas de segundo.	
         cs=Math.round(cs); //redondear las centésimas	
         sg=cr.getSeconds(); //segundos 	
         mn=cr.getMinutes(); //minutos 	
         ho=cr.getHours()-21; //horas 	
            //poner siempre 2 cifras en los números			 
         if (cs<10) {cs="00"+cs;} 
         if (cs<100) {cs="0"+cs;} 
         if (sg<10) {sg="0"+sg;} 
         if (mn<10) {mn="0"+mn;} 
        
            //llevar resultado al visor.			 
         visor.innerHTML=ho+" : "+mn+" : "+sg+" : "+cs; 
         }
    
    //parar el cronómetro
    function parar() { 
         clearInterval(elcrono); //parar el crono
         marcha=0; //indicar que está parado.
         document.cron.boton2.value="Continuar"; //cambiar el estado del botón
         }	
    
    //Continuar una cuenta empezada y parada.
    function continuar() {
         emp2=new Date(); //fecha actual
         emp2=emp2.getTime(); //pasar a tiempo Unix
         emp3=emp2-cro; //restar tiempo anterior
         emp=new Date(); //nueva fecha inicial para pasar al temporizador 
         emp.setTime(emp3); //datos para nueva fecha inicial.
         elcrono=setInterval(tiempo,10); //activar temporizador
         marcha=1; //indicar que esta en marcha
         document.cron.boton2.value="Parar"; //Cambiar estado del botón
         document.cron.boton1.disabled=false; //activar boton 1 si estuviera desactivado
         }
    
    
    //Volver al estado inicial
    function reiniciar() {
         if (marcha==1) {  //si el cronómetro está en marcha:
             clearInterval(elcrono); //parar el crono
             marcha=0;	//indicar que está parado
             }
                 //en cualquier caso volvemos a los valores iniciales
         cro=0; //tiempo transcurrido a cero
         visor.innerHTML = "0 00 00 00"; //visor a cero
         document.cron.boton1.value="Empezar"; //estado inicial primer botón
         document.cron.boton2.value="Parar"; //estado inicial segundo botón
         document.cron.boton2.disabled=true;  //segundo botón desactivado	 
         document.cron.boton3.disabled=true;  //tercer botón desactivado	 
         }	
    
    
    function vuelta(){
        
        
    }
            </script>
    </body>
</html>

blog/templates/form.html
{% load static %}
{% load staticfiles %}
<html>
    <head>
    <title>Formulario</title>
    <link type="text/css" href="{% static 'css/form.css'%}" rel="stylesheet" media="screen,projection"/>
    </head>
    <body>
        <td  colspan="5"><input class="inp1" type="text"  ></td>
        <td  colspan="5"><input class="inp2" type="text"  ></td>
        
        <div class="form">
            <h3>Usuario:</h3>
            <h3 id="pass">Contrasenia:</h3>     
            <form><div id="div" onmouseover="move()" class="div" ><h5>Click me!!</h5></div></form>                
        </div>

     <script>
    function move() {
    var div = document.getElementById("div");
    var a = Math.random(1,10);
    console.log(a);
    var a = a*300;
    var b = Math.random(1,10);
    var b = b*200;
    div.style.left = a;
    div.style.top = b;
             </script>

    </body>
</html>

blog/templates/imagenes.html
{% load static %}
{% load staticfiles %}
<html>
    <head>
    <link type="text/css" href="{% static 'css/imagenes.css'%}" rel="stylesheet" media="screen,projection"/>
    </head>
    <body onload="both()">
        <div class="title">
            <div id="myBar"></div>
        
        </div>
        <br>
        <br>
        <div class="img">
             <img id="image" src="{% static 'images/1.jpeg' %}">
             <br>
            <div id="myProgress">
</div>
        
        </div>
        <script>
        function both(){
        imageChanger();
        move();
}
        
        function imageChanger(){
            var image = document.getElementById("image");
            switch(Math.floor(Math.random() * 8) + 1){
                case 1 :
                    image.src = "{% static 'images/1.jpeg' %}";
                    break;
                case 2 :
                    image.src = "{% static 'images/2.jpeg' %}";
                    break;
                case 3:
                    image.src = "{% static 'images/3.jpeg' %}";
                    break;
                case 4:
                    image.src = "{% static 'images/4.jpeg' %}";
                    break;                                        

}
            setTimeout(imageChanger, 5000);
        }
        
function move() {
   var elem = document.getElementById("myBar");   
   var width = 1;
   var id = setInterval(frame, 50);
  
function frame() {
    if (width >= 100) {
        clearInterval(id);
        move();
    } else {
      width++; 
      elem.style.width = width + '%'; 
      console.log(width);
    }
  }
}</script>
    </body>
    
</html>

blog/templates/list.html
{% extends "base.html" %}
{% block sidebar %}
{% load static %}
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
        a { margin-left: 15px; }

    </style>
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for month in months %}
            {% ifchanged month.0 %} {{ month.0 }} <br /> {% endifchanged %}

        {% endfor %}
        </p>
    </div>
{% endblock %}

{% block content %}

{% for post in post_list %}
<div class="container">
	 <div id="blog" class="row"> 

                 <div class="col-md-10 blogShort">
                     <h1>{{post.title}}</h1>
                     <img src="{% static 'fotos/' %}{{post.nombre_imagen}}" class="pull-left img-responsive thumb margin10 img-thumbnail">
                     <article><p>
                         {{post.body}}
                         </p></article>
                     <a class="btn btn-blog pull-right marginBottom10" href="{% url 'index:post' post.id %}">VER</a> 
                 </div>                 
               <div class="col-md-12 gap10"></div>
             </div>
</div>{% endfor %}
                
                 







        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">Entradas mas nuevas &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Pagina {{ posts.number }} de {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; Post mas viejitos</a>
                {% endif %}
            </span>
        </div>
        {% endif %}



{% endblock %}

blog/templates/post.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block content %}
<script src="http://www.w3schools.com/lib/w3data.js"></script>
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .comment { border: 1px solid #eee; padding: 4px; margin-bottom: 12px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .messages { margin-left: 20px; }
        .title { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ccc;color: #000; padding-left: 4px; }

        #addc { width: 508px; background: #f5f5f5; padding: 3px; padding-bottom: 8px;
            border-bottom: 1px dotted #aaa;
            }
        #cform { background: #f5f5f5; width: 506px; padding: 4px; padding-bottom: 0px; }
        #submit { text-align: right; margin-right: 50px; width: 500px; margin-top: -5px; }

        ul { margin-bottom: 30px; }

    </style>
    <div class="main">

        <!-- Messages  -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <!-- Post  -->
        <ul>
            <div class="blog-title" style="margin-top:3%;margin-left:40%"><h3>{{ post.title }}</h3></div>
            <ul style="margin-bottom:5%" >
             <div>
                 {% if post.url_post|length > 0 %}
                 {% include post.url_post %}
                 {% else %}
                 
                 {% endif %}
                 {{post.body}}
                
                </div>
                
                <div style="margin-bottom:10%" w3-include-html="{% static 'tp/ej'%}{{post.id}}.html"></object></div>

            <!-- Comments  -->
            {% if comments %}
                <p style="margin-bottom:2%">Commentarios:</p>
            {% endif %}

            <form action="" method="POST">{% csrf_token %}
            {% for comment in comments %}
                <div class="comment">
                    <div class="time"> {{ comment.author }}    | {{ comment.created }}</div>
                    <div class="body">{{ comment.body|linebreaks }}</div>
                    {% if user.is_staff %}

                    {% endif %}
                </div>
            {% endfor %}

            {% if user.is_staff and comments %}
                
                <br />
            {% endif %}
            </form>

            
            <!-- Comment form  -->
            <form style="background-color:#607d8b;width:100%;height:30%;border-radius:1%" action="" method="POST">
            
                {% csrf_token %}
                <div style="margin-bottom:0%"class="input-group">
				<div  style="margin-top:5%;margin-left:5%;width:15%;color:black"><h5>Comentá:<h5/></div>
                    <input style="width:20%;margin-left:11%" type="text" length="10" id="input_text" class="form-control" placeholder="Autor" name='author' aria-describedby="basic-addon1"/>
                    <textarea style="width:41%;height:25%;margin-left:11%" length="120" id="textarea1" class="materialize-textarea" placeholder="Comentario" name='content' aria-describedby="basic-addon1"></textarea>
                    <br>
                <div style="margin-left:-30%;margin-top:5%" id="submit"><input type="submit" value="Enviar"></div>
</div>

            
            </form>
        </ul>

    </div>

{% endblock %}